---

- name: add certbot ppa
  when: frontend_ssl.certbot.active|bool and frontend_ssl.enabled|bool
  apt_repository: repo='ppa:certbot/certbot'

- name: install certbot
  when: frontend_ssl.certbot.active|bool and frontend_ssl.enabled|bool
  apt: name=certbot state=present

- name: install nginx
  apt: name=nginx state=present

- name: enable default nginx vhost
  when: frontend_ssl.certbot.active|bool and frontend_ssl.enabled|bool
  file:
    src=/etc/nginx/sites-available/default
    dest=/etc/nginx/sites-enabled/default
    state=link

- name: start nginx
  when: frontend_ssl.certbot.active|bool and frontend_ssl.enabled|bool
  service:
    name: nginx
    state: restarted
    use: service

- name: set up ssl cert
  when: frontend_ssl.certbot.active|bool and frontend_ssl.enabled|bool
  command: >
    certbot certonly --non-interactive --agree-tos --webroot
    -w {{ frontend_certbot_webroot }}
    -d {{ frontend_domain_name }}
    --email {{ frontend_ssl.certbot.email }}



- name: disable default nginx vhost
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: configure nginx
  template:
    src=templates/nginx.conf.j2
    dest=/etc/nginx/conf.d/nginx.conf

- name: create our nginx vhost
  template:
    src=templates/nginx_vhost.conf.j2
    dest=/etc/nginx/sites-available/{{ frontend_config_name }}

- name: symlink our nginx vhost
  file:
    src=/etc/nginx/sites-available/{{ frontend_config_name }}
    dest=/etc/nginx/sites-enabled/{{ frontend_config_name }} state=link
  notify:
    - restart nginx

- name: enable nginx
  service:
    name: nginx
    state: started
    enabled: yes
    use: service
